services:
  users.command.api:
    image: ${DOCKER_REGISTRY-}commandapi
    container_name: users-command-api
    build:
      context: .
      dockerfile: src/Command.Api/Dockerfile
    depends_on:
      - users.database

  users.query.api:
    image: ${DOCKER_REGISTRY-}queryapi
    container_name: users-query-api
    build:
      context: .
      dockerfile: src/Query.Api/Dockerfile
    depends_on:
      - users.database

  users.database:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: users-db
